"""faust loop editor — diff generation and safe file writing for Phase 2.

This module is the only place in the codebase that is permitted to write
production source files on behalf of the loop.  All writes go through
``write_approved_change`` which validates the target path before touching
the filesystem.

Safety contract (NEVER relaxed):
  - ``write_approved_change`` rejects any path that resolves outside the
    project-relative ``src/`` directory.
  - ``build_unified_diff`` is a pure function; it has no side-effects.
  - No subprocess calls live in this module.
"""

from __future__ import annotations

import difflib
from dataclasses import dataclass, field
from pathlib import Path
from typing import List


# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------

@dataclass
class EditProposal:
    """Carries a single proposed code change through the approval gate.

    Attributes:
        path: Project-relative path of the file to edit (e.g. ``src/faust/foo.py``).
        original: Current file content as a string.
        proposed: Proposed replacement content as a string.
        diff: Unified diff string (generated by ``build_unified_diff``).
        description: Human-readable summary shown in the proposal panel.
        test_targets: Scoped pytest node-ids to run after an approved write.
    """
    path: str
    original: str
    proposed: str
    diff: str
    description: str = ""
    test_targets: List[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Diff generation  (pure — no filesystem access)
# ---------------------------------------------------------------------------

def build_unified_diff(original: str, proposed: str, path: str) -> str:
    """Return a unified diff string comparing *original* and *proposed*.

    Args:
        original: The current content of the file.
        proposed: The proposed replacement content.
        path:     File path used only as label in the diff header.

    Returns:
        A unified-diff string (may be empty if the contents are identical).

    This function is pure: it reads nothing from disk and writes nothing.
    """
    original_lines = original.splitlines(keepends=True)
    proposed_lines = proposed.splitlines(keepends=True)

    diff_lines = list(
        difflib.unified_diff(
            original_lines,
            proposed_lines,
            fromfile=f"a/{path}",
            tofile=f"b/{path}",
        )
    )
    return "".join(diff_lines)


# ---------------------------------------------------------------------------
# Safe writer
# ---------------------------------------------------------------------------

def write_approved_change(path: str, content: str) -> Path:
    """Write *content* to *path* after validating it is inside ``src/``.

    This is the ONLY function in the codebase that writes production files
    on behalf of ``faust loop``.  It enforces the Step 11 safety boundary:
    no writes outside ``src/`` are permitted.

    Args:
        path:    Project-relative path (e.g. ``src/faust/foo.py``).
        content: Full replacement file content.

    Returns:
        The resolved absolute ``Path`` of the file that was written.

    Raises:
        ValueError: If the resolved path is not inside the ``src/``
                    directory of the current working tree.
    """
    target = Path(path)

    # Resolve both the target and the src/ anchor against cwd so that
    # relative path tricks (../../etc/passwd) are caught.
    resolved = (Path.cwd() / target).resolve()
    src_root = (Path.cwd() / "src").resolve()

    try:
        resolved.relative_to(src_root)
    except ValueError:
        raise ValueError(
            f"Write rejected: '{path}' resolves to '{resolved}' which is "
            f"outside the allowed src/ boundary ('{src_root}').  "
            "No file was written."
        )

    resolved.parent.mkdir(parents=True, exist_ok=True)
    resolved.write_text(content, encoding="utf-8")
    return resolved
